/**
 * Discovery orchestrator.
 *
 * For a given company, dispatch the active connectors in parallel, dedupe,
 * and persist results. Returns a per-source-type report.
 *
 * The orchestrator is the ONLY entry point that should be called from
 * onboarding, scheduler, or a manual admin refresh.
 */

import crypto from "node:crypto";
import { logger } from "../logger.js";
import { supabaseRest } from "../research/supabase-rest.js";
import { discoverBseAnnouncements } from "./connectors/bse-announcements.js";
import { discoverGoogleNewsRss } from "./connectors/google-news.js";
import { persistDiscoveredItems } from "./persister.js";
import type { DiscoveredItem, DiscoveryReport, SourceType } from "./types.js";

// Ticker → BSE scrip code map. For MVP we hardcode a small set that maps
// to companies present in Supabase. In production this will live in
// `companies.metadata.bse_scrip_code`.
const TICKER_TO_BSE_SCRIP: Record<string, string> = {
  RELIANCE: "500325",
  TCS: "532540",
  INFY: "500209",
  HDFCBANK: "500180",
  ITC: "500875",
  LT: "500510",
  BHARTIARTL: "532454",
  ICICIBANK: "532174",
  HDFC: "500010",
  KOTAKBANK: "500247",
  SBIN: "500112",
  MARUTI: "532500",
  ASIANPAINT: "500820",
  TITAN: "500114",
};

interface CompanyRow {
  id: string;
  ticker: string;
  name: string;
  legal_name?: string | null;
  is_active?: boolean;
}

export async function findCompanyByTicker(ticker: string): Promise<CompanyRow | null> {
  const t = ticker.toUpperCase().trim();
  const rows = await supabaseRest<CompanyRow[]>(
    "GET",
    `/companies?ticker=eq.${encodeURIComponent(t)}&select=id,ticker,name,legal_name,is_active`,
  );
  return rows[0] ?? null;
}

export interface DiscoveryOptions {
  daysBackNews?: number;         // For scheduled refresh, keep small
  daysBackFilings?: number;
  enableNews?: boolean;
  enableFilings?: boolean;
}

const EMPTY_OUTCOME = {
  fetched: 0,
  stored: 0,
  skippedDuplicate: 0,
};

async function upsertRunRecord(
  runId: string,
  companyId: string,
  status: "started" | "completed" | "failed",
  detail: unknown = null,
) {
  try {
    await supabaseRest("POST", "/research_jobs", {
      prefer: "return=minimal",
      body: {
        id: runId,
        company_id: companyId,
        status: status === "started" ? "discovery_running" : status === "completed" ? "discovery_complete" : "discovery_failed",
        started_at: new Date().toISOString(),
        completed_at: status !== "started" ? new Date().toISOString() : null,
        error_message: status === "failed" ? String(detail).slice(0, 500) : null,
        sections_requested: 0,
        sections_completed: 0,
        sections_failed: 0,
      },
    });
  } catch (err) {
    // research_jobs.id is generated by DB — retry as PATCH ignoring collision
    logger.warn({ err }, "research_jobs upsert failed (non-fatal)");
  }
}

export async function discoverForCompany(
  ticker: string,
  options: DiscoveryOptions = {},
): Promise<DiscoveryReport> {
  const {
    daysBackNews = 21,
    daysBackFilings = 365,
    enableNews = true,
    enableFilings = true,
  } = options;

  const runId = crypto.randomUUID();
  const startedAt = new Date().toISOString();

  const company = await findCompanyByTicker(ticker);
  if (!company) {
    throw new Error(`Company ticker "${ticker}" not found in Supabase`);
  }

  await upsertRunRecord(runId, company.id, "started");

  const bseScrip = TICKER_TO_BSE_SCRIP[company.ticker.toUpperCase()];

  const bySourceType: DiscoveryReport["bySourceType"] = {
    annual_report: { ...EMPTY_OUTCOME },
    concall: { ...EMPTY_OUTCOME },
    credit_rating: { ...EMPTY_OUTCOME },
    filing: { ...EMPTY_OUTCOME },
    investor_presentation: { ...EMPTY_OUTCOME },
    news: { ...EMPTY_OUTCOME },
  };

  // Run connectors in parallel — no LLM cost, just HTTP.
  const [newsItems, filingItems] = await Promise.all([
    enableNews
      ? discoverGoogleNewsRss({
          companyId: company.id,
          companyName: company.name,
          aliases: [company.legal_name ?? "", company.ticker].filter(Boolean),
          maxItems: Math.max(20, Math.min(60, daysBackNews * 2)),
        }).catch((err) => {
          logger.error({ err }, "Google News connector failed");
          bySourceType.news.error = String(err);
          return [] as DiscoveredItem[];
        })
      : Promise.resolve([] as DiscoveredItem[]),
    enableFilings && bseScrip
      ? discoverBseAnnouncements({
          companyId: company.id,
          bseScripCode: bseScrip,
          companyName: company.name,
          daysBack: daysBackFilings,
        }).catch((err) => {
          logger.error({ err }, "BSE announcements connector failed");
          bySourceType.filing.error = String(err);
          return [] as DiscoveredItem[];
        })
      : Promise.resolve([] as DiscoveredItem[]),
  ]);

  if (!bseScrip && enableFilings) {
    bySourceType.filing.error = `No BSE scrip code registered for ticker ${company.ticker}`;
  }

  const allItems = [...newsItems, ...filingItems];
  for (const it of allItems) bySourceType[it.sourceType].fetched += 1;

  const outcome = await persistDiscoveredItems(company.id, allItems);
  for (const key of Object.keys(outcome) as SourceType[]) {
    bySourceType[key].stored += outcome[key].stored;
    bySourceType[key].skippedDuplicate += outcome[key].skippedDuplicate;
    if (outcome[key].errors.length > 0 && !bySourceType[key].error) {
      bySourceType[key].error = outcome[key].errors[0];
    }
  }

  const finishedAt = new Date().toISOString();
  const totalStored = Object.values(bySourceType).reduce((n, o) => n + o.stored, 0);

  await upsertRunRecord(runId, company.id, "completed", { totalStored });

  return {
    companyId: company.id,
    ticker: company.ticker,
    runId,
    startedAt,
    finishedAt,
    bySourceType,
    totalStored,
  };
}
