import { useState, type ReactNode } from 'react';
import { ArrowDownRight, ArrowRight, ArrowUpRight, Check, ChevronDown, CircleHelp, HelpCircle, Info, MoveUp, Scale, ShieldCheck, Target, WalletCards } from 'lucide-react';
import {
  balanceSheet,
  cashFlow,
  commentary,
  company,
  crossChecks,
  earningsDrivers,
  financials,
  monitor,
  news,
  overall,
  questions,
  redFlags,
  segments,
  shareholding,
  snapshot,
  valuation,
} from '@/data/reliance';
import { DataTag, Expandable, Footer, Header, MiniChart, ReportRail, SectionHeading, SignalPill, SourceNote, StatusIcon } from '@/components/stocklens-ui';

function Metric({ label, value, note, accent = false }: { label: string; value: string; note?: string; accent?: boolean }) {
  return <div className="border-l border-[hsl(var(--border))] pl-4" data-testid={`metric-${label.toLowerCase().replaceAll(' ', '-')}`}><p className="eyebrow">{label}</p><p className={`mt-2 font-display text-[25px] tracking-[-.04em] ${accent ? 'text-[hsl(var(--primary))]' : ''}`}>{value}</p>{note && <p className="mt-1 text-[11px] leading-relaxed text-[hsl(var(--muted-foreground))]">{note}</p>}</div>;
}

function ReportSection({ children, className = '', id }: { children: ReactNode; className?: string; id: string }) {
  return <section id={id} className={`section-anchor mx-auto max-w-[1380px] px-5 py-16 lg:px-10 lg:py-24 ${className}`}>{children}</section>;
}

function Bar({ value, color = 'primary' }: { value: number; color?: string }) {
  const colorClass = color === 'orange' ? 'bg-[hsl(var(--accent))]' : color === 'blue' ? 'bg-[hsl(var(--chart-4))]' : color === 'gold' ? 'bg-[hsl(var(--chart-3))]' : 'bg-[hsl(var(--primary))]';
  return <div className="h-2 overflow-hidden rounded-full bg-[hsl(var(--muted))]"><div className={`h-full rounded-full ${colorClass} transition-all`} style={{ width: `${value}%` }} /></div>;
}

function segmentTone(accent: string) {
  if (accent === 'orange') return 'bg-[hsl(var(--accent)/.12)] text-[hsl(var(--accent))]';
  if (accent === 'gold') return 'bg-[hsl(var(--chart-3)/.14)] text-[hsl(35_62%_32%)]';
  if (accent === 'blue') return 'bg-[hsl(var(--chart-4)/.12)] text-[hsl(var(--chart-4))]';
  if (accent === 'plum') return 'bg-[hsl(var(--chart-5)/.12)] text-[hsl(var(--chart-5))]';
  return 'bg-[hsl(var(--primary)/.12)] text-[hsl(var(--primary))]';
}

function RiskRow({ title, signal, finding, why }: { title: string; signal: 'LOW' | 'WATCH' | 'HIGH'; finding: string; why: string }) {
  return <div className="grid gap-4 border-b border-[hsl(var(--border))] py-5 last:border-0 md:grid-cols-[1.1fr_1fr_1fr_auto] md:items-start" data-testid={`row-cross-check-${title.toLowerCase().replaceAll(' ', '-')}`}><div className="flex items-start gap-3"><span className="mt-1 h-2 w-2 rounded-full bg-[hsl(var(--primary))]" /><p className="text-sm font-semibold">{title}</p></div><div><p className="eyebrow">Finding</p><p className="mt-1 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">{finding}</p></div><div><p className="eyebrow">Why it matters</p><p className="mt-1 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">{why}</p></div><SignalPill signal={signal} /></div>;
}

export default function Research() {
  const [showAllQuestions, setShowAllQuestions] = useState(false);
  const [saved, setSaved] = useState(false);
  return (
    <div className="min-h-[100dvh]">
      <Header report />
      <ReportRail />
      <main>
        <section id="overview" className="section-anchor border-b border-[hsl(var(--border))] bg-[hsl(var(--secondary)/.4)]">
          <div className="mx-auto max-w-[1380px] px-5 pb-14 pt-12 lg:px-10 lg:pb-20 lg:pt-16">
            <div className="flex flex-col justify-between gap-10 lg:flex-row lg:items-end">
              <div className="max-w-3xl">
                <div className="reveal flex flex-wrap items-center gap-2"><DataTag tone="fact">FACT</DataTag><span className="eyebrow">COMPANY RESEARCH / 01</span><span className="font-mono-stock text-[10px] text-[hsl(var(--muted-foreground))]">27 JUN 2024</span></div>
                <h1 className="reveal reveal-delay-1 mt-6 font-display text-[clamp(47px,7vw,90px)] leading-[.89] tracking-[-.07em]">Reliance<br /><span className="text-[hsl(var(--primary))]">in plain sight.</span></h1>
                <p className="reveal reveal-delay-2 mt-6 max-w-2xl text-base leading-[1.7] text-[hsl(var(--muted-foreground))]">The whole picture of India’s most watched conglomerate — from the refinery that still pays the bills to the digital, retail and new-energy bets shaping what comes next.</p>
              </div>
              <div className="flex shrink-0 items-center gap-3">
                <button type="button" onClick={() => setSaved(!saved)} data-testid="button-save-report" className={`flex items-center gap-2 rounded-xl border px-4 py-3 text-sm font-semibold transition-colors ${saved ? 'border-[hsl(var(--primary)/.3)] bg-[hsl(var(--primary)/.08)] text-[hsl(var(--primary))]' : 'border-[hsl(var(--border))] bg-[hsl(var(--card))]'}`}><ShieldCheck size={16} /> {saved ? 'Saved locally' : 'Save report'}</button>
              </div>
            </div>
            <div className="mt-12 grid gap-x-8 gap-y-8 border-t border-[hsl(var(--border))] pt-7 sm:grid-cols-2 lg:grid-cols-4">
              <Metric label="NSE · BSE" value="RELIANCE" note="Energy, Oil & Gas · Conglomerate" />
              <Metric label="Sample price" value={company.price} note={`${company.priceChange} (${company.priceChangePct}) · ${company.asOf}`} accent />
              <Metric label="Market cap" value={company.marketCap} note="Illustrative market value" />
              <Metric label="Our posture" value="Understand first" note="No buy / sell recommendation" />
            </div>
          </div>
        </section>

        <ReportSection id="business">
          <SectionHeading eyebrow="01 / Business" title="What does Reliance actually do?"><><DataTag tone="analysis">ANALYSIS</DataTag><span className="ml-2">It is best understood as several large businesses sharing one balance sheet — not one simple company.</span></></SectionHeading>
          <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
            <div className="paper-card rounded-2xl p-6 md:p-8"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[hsl(var(--primary)/.1)] text-[hsl(var(--primary))]"><Target size={19} /></div><div><p className="eyebrow">The simple version</p><h3 className="mt-1 font-display text-2xl">One group. Five engines.</h3></div></div><DataTag tone="fact">FACT</DataTag></div><p className="mt-7 max-w-2xl text-[17px] leading-[1.7] text-[hsl(var(--foreground)/.78)]">Reliance buys crude oil and turns it into fuels and materials. That cash engine funds Jio’s connectivity, Retail’s national footprint and a large bet on new energy. Media and other businesses sit around the edges.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-[hsl(var(--secondary)/.7)] p-4"><p className="eyebrow">Today</p><p className="mt-2 text-sm leading-relaxed">O2C is still the largest profit pool. Digital is the clearest source of recurring growth.</p></div><div className="rounded-xl bg-[hsl(var(--accent)/.08)] p-4"><p className="eyebrow text-[hsl(var(--accent))]">Tomorrow</p><p className="mt-2 text-sm leading-relaxed">Retail and new energy could change the mix, but need capital and patient execution.</p></div></div></div>
            <div className="paper-card rounded-2xl p-6 md:p-8"><p className="eyebrow">How does it make money?</p><div className="mt-6 grid gap-5">{[['01', 'Buy & transform', 'Crude → fuels, polymers, chemicals'], ['02', 'Connect & collect', 'Subscribers → monthly digital revenue'], ['03', 'Scale & compound', 'Stores, brands → margin + volume'], ['04', 'Build for later', 'Capex → future energy economics']].map(([n, t, d]) => <div key={n} className="flex gap-4"><span className="font-mono-stock text-[11px] text-[hsl(var(--accent))]">{n}</span><div><p className="text-sm font-semibold">{t}</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{d}</p></div></div>)}</div><SourceNote /></div>
          </div>
          <div className="mt-14 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{segments.map((segment) => <div key={segment.short} className="paper-card group rounded-2xl p-5 transition-transform duration-300 hover:-translate-y-1" data-testid={`card-business-${segment.short.toLowerCase().replaceAll(' ', '-')}`}><div className="flex items-center justify-between"><span className={`grid h-9 w-9 place-items-center rounded-lg font-mono-stock text-[11px] font-medium ${segmentTone(segment.accent)}`}>{segment.short.slice(0, 2).toUpperCase()}</span><span className="font-mono-stock text-xl text-[hsl(var(--foreground))]">{segment.share}</span></div><h3 className="mt-6 font-display text-xl">{segment.name}</h3><Expandable title="What it does" testId={`${segment.short}-does`}><span>{segment.does}</span></Expandable><Expandable title="How it makes money" testId={`${segment.short}-makes`}><span>{segment.makes}</span></Expandable><Expandable title="Why it matters" testId={`${segment.short}-why`}><span>{segment.why}</span></Expandable></div>)}</div>
          <SourceNote>Sample segment contribution to group EBITDA · illustrative, not a reported split</SourceNote>
        </ReportSection>

        <div className="border-y border-[hsl(var(--border))] bg-[hsl(var(--secondary)/.35)]">
          <ReportSection id="financials">
            <SectionHeading eyebrow="02 / Financials" title="What changed in the numbers?"><><DataTag tone="fact">FACT</DataTag><span className="ml-2">The headline is mixed: revenue softened, but mix and digital momentum protected operating profit.</span></></SectionHeading>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{financials.map((metric) => <div key={metric.label} className="paper-card rounded-xl p-4" data-testid={`card-financial-${metric.label.toLowerCase().replaceAll(' ', '-')}`}><div className="flex items-start justify-between"><div><p className="eyebrow">{metric.label}</p><p className="mt-2 font-display text-2xl tracking-[-.04em]">{metric.value}</p></div><span className={`flex items-center gap-0.5 font-mono-stock text-[10px] ${metric.direction === 'up' ? 'text-[hsl(var(--primary))]' : 'text-[hsl(var(--accent))]'}`}>{metric.direction === 'up' ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}{metric.change}</span></div><div className="mt-4"><MiniChart values={metric.values} color={metric.direction === 'up' ? 'hsl(var(--primary))' : 'hsl(var(--accent))'} /></div><p className="mt-2 font-mono-stock text-[9px] uppercase tracking-[.08em] text-[hsl(var(--muted-foreground))]">FY18 — FY24 sample trend</p></div>)}</div>
            <div className="mt-8 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-2xl bg-[hsl(var(--primary))] p-6 text-[hsl(var(--primary-foreground))] md:p-8"><div className="flex items-center justify-between"><p className="eyebrow text-[hsl(var(--primary-foreground)/.6)]">What’s happening?</p><DataTag tone="analysis">ANALYSIS</DataTag></div><h3 className="mt-7 font-display text-3xl leading-tight">Profit held up better than revenue because the business mix is changing.</h3><p className="mt-5 text-sm leading-relaxed text-[hsl(var(--primary-foreground)/.72)]">A softer commodity environment pulled down the top line. Higher-margin digital services and a better O2C mix helped defend EBITDA. That is useful — but it is not the same as every business accelerating.</p></div><div className="paper-card rounded-2xl p-6 md:p-8"><p className="eyebrow">Why did earnings change?</p><div className="mt-3">{earningsDrivers.map((driver) => <Expandable key={driver.title} title={driver.title} testId={`earnings-${driver.title.toLowerCase().replaceAll(' ', '-')}`}><span>{driver.text}</span></Expandable>)}</div></div></div>
            <SourceNote>Consolidated sample figures · ₹ lakh crore unless stated otherwise</SourceNote>
          </ReportSection>
        </div>

        <ReportSection id="cash-flow">
          <SectionHeading eyebrow="03 / Cash flow" title="Does profit turn into cash?"><><DataTag tone="analysis">ANALYSIS</DataTag><span className="ml-2">Yes, for now. The important qualifier is how much of that cash goes straight back into growth.</span></></SectionHeading>
          <div className="grid gap-3 md:grid-cols-4">{cashFlow.map((item, i) => <div key={item.label} className={`rounded-2xl p-5 ${i === 3 ? 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]' : 'paper-card'}`} data-testid={`card-cash-${item.label.toLowerCase().replaceAll(' ', '-')}`}><div className="flex items-center justify-between"><p className={`eyebrow ${i === 3 ? 'text-[hsl(var(--primary-foreground)/.6)]' : ''}`}>{item.label}</p><span className={`text-xs ${i === 3 ? 'text-[hsl(var(--accent))]' : 'text-[hsl(var(--primary))]'}`}>{i === 0 ? <WalletCards size={18} /> : i === 1 ? <ArrowDownRight size={18} /> : i === 2 ? <MoveUp size={18} /> : <Check size={18} />}</span></div><p className="mt-8 font-display text-3xl tracking-[-.05em]">{item.value}</p><p className={`mt-2 text-xs ${i === 3 ? 'text-[hsl(var(--primary-foreground)/.65)]' : 'text-[hsl(var(--muted-foreground))]'}`}>{item.sub}</p></div>)}</div>
          <div className="mt-8 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="paper-card rounded-2xl p-6 md:p-8"><p className="eyebrow">The bridge</p><div className="mt-7 flex flex-wrap items-center gap-2 sm:flex-nowrap">{cashFlow.map((item, i) => <div key={item.label} className="flex min-w-[120px] flex-1 items-center gap-2"><div className="flex-1"><p className="font-mono-stock text-[9px] uppercase text-[hsl(var(--muted-foreground))]">{item.label}</p><div className="mt-2"><Bar value={[48, 88, 58, 35][i]} color={i === 3 ? 'orange' : 'primary'} /></div></div>{i < 3 && <ArrowRight size={15} className="mt-5 shrink-0 text-[hsl(var(--muted-foreground))]" />}</div>)}</div></div><div className="rounded-2xl bg-[hsl(var(--accent)/.1)] p-6 md:p-8"><div className="flex items-center gap-2 text-[hsl(var(--accent))]"><CircleHelp size={18} /><p className="eyebrow text-[hsl(var(--accent))]">Why different from profit?</p></div><p className="mt-5 text-sm leading-[1.75] text-[hsl(var(--foreground)/.78)]">Profit includes non-cash accounting items and timing differences. Cash flow also reflects working capital — when customers pay, inventory moves and suppliers are paid. In this sample, operating cash flow is higher than profit, which is a healthy sign.</p></div></div>
          <SourceNote>Cash flow figures are illustrative sample data and do not represent live financial statements</SourceNote>
        </ReportSection>

        <div className="border-y border-[hsl(var(--border))] bg-[hsl(var(--secondary)/.35)]">
          <ReportSection id="balance-sheet">
            <SectionHeading eyebrow="04 / Balance sheet" title="How healthy is the base?"><><DataTag tone="fact">FACT</DataTag><span className="ml-2">Liquidity is a buffer. The question is whether the asset base starts earning fast enough for the next cycle.</span></></SectionHeading>
            <div className="paper-card overflow-hidden rounded-2xl"><div className="grid gap-0 md:grid-cols-5">{balanceSheet.map((item) => <div key={item.label} className="border-b border-[hsl(var(--border))] p-5 last:border-0 md:border-b-0 md:border-r md:last:border-r-0" data-testid={`metric-balance-${item.label.toLowerCase().replaceAll(' ', '-')}`}><p className="eyebrow">{item.label}</p><p className="mt-3 font-display text-2xl">{item.value}</p><p className={`mt-2 font-mono-stock text-[10px] ${item.tone === 'positive' ? 'text-[hsl(var(--primary))]' : item.tone === 'watch' ? 'text-[hsl(var(--accent))]' : 'text-[hsl(var(--muted-foreground))]'}`}>{item.delta} vs prior year</p></div>)}</div></div>
            <div className="mt-8 grid gap-5 lg:grid-cols-2"><div className="paper-card rounded-2xl p-6 md:p-8"><p className="eyebrow">What changed?</p><p className="mt-5 text-lg leading-relaxed">Cash and liquid investments grew, while gross debt also moved higher to fund the group’s investment programme. The balance sheet has room — but not an excuse to ignore returns.</p><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[hsl(var(--primary)/.08)] p-4"><p className="eyebrow text-[hsl(var(--primary))]">Buffer</p><p className="mt-2 text-sm font-semibold">₹2.09L cr liquid</p></div><div className="rounded-xl bg-[hsl(var(--accent)/.09)] p-4"><p className="eyebrow text-[hsl(var(--accent))]">Watch</p><p className="mt-2 text-sm font-semibold">₹3.10L cr debt</p></div></div></div><div className="paper-card rounded-2xl p-6 md:p-8"><div className="flex items-center gap-2"><Info size={17} className="text-[hsl(var(--chart-4))]" /><p className="eyebrow">Is anything unusual?</p></div><p className="mt-5 text-sm leading-[1.75] text-[hsl(var(--muted-foreground))]">Receivables grew faster than revenue. That relationship is worth monitoring, but it is an observation about reported balances — not an accusation of wrongdoing. Timing, business mix and billing terms can all play a role.</p><DataTag tone="uncertainty">UNCERTAINTY</DataTag></div></div>
          </ReportSection>
        </div>

        <ReportSection id="risks">
          <SectionHeading eyebrow="05 / Cross-statement analysis" title="Does the financial story actually make sense?"><><DataTag tone="inference">INFERENCE</DataTag><span className="ml-2">Five relationships investors can keep checking as new results arrive.</span></></SectionHeading>
          <div className="paper-card rounded-2xl px-5 md:px-8">{crossChecks.map((item) => <RiskRow key={item.title} {...item} />)}</div>
          <div className="mt-14 grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[hsl(var(--accent))]">Red flags, without drama</p><h3 className="mt-4 font-display text-4xl leading-[.98] tracking-[-.04em]">Things investors should watch.</h3><p className="mt-5 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">These are prompts for better questions, not allegations or predictions.</p></div><div className="grid gap-0 border-t border-[hsl(var(--border))]">{redFlags.map((flag) => <div key={flag.no} className="grid gap-4 border-b border-[hsl(var(--border))] py-5 sm:grid-cols-[42px_1fr_auto] sm:items-start" data-testid={`row-red-flag-${flag.no}`}><span className="font-mono-stock text-xs text-[hsl(var(--accent))]">{flag.no}</span><div><h4 className="text-sm font-semibold">{flag.title}</h4><p className="mt-2 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">{flag.body}</p></div><SignalPill signal={flag.signal} /></div>)}</div></div>
        </ReportSection>

        <div className="border-y border-[hsl(var(--border))] bg-[hsl(var(--secondary)/.35)]">
          <ReportSection id="management">
            <SectionHeading eyebrow="06 / Management" title="What has been promised — and delivered?"><><DataTag tone="analysis">ANALYSIS</DataTag><span className="ml-2">The group’s ambition is not in doubt. The useful question is how each promise is progressing.</span></></SectionHeading>
            <div className="paper-card overflow-hidden rounded-2xl"><div className="hidden grid-cols-[1.2fr_.45fr_1fr] border-b border-[hsl(var(--border))] bg-[hsl(var(--muted)/.45)] px-6 py-3 font-mono-stock text-[9px] uppercase tracking-[.1em] text-[hsl(var(--muted-foreground))] md:grid"><span>Management promise</span><span>Status</span><span>Our reading</span></div>{commentary.map((item) => <div key={item.promise} className="grid gap-3 border-b border-[hsl(var(--border))] p-5 last:border-0 md:grid-cols-[1.2fr_.45fr_1fr] md:items-center md:px-6"><div className="text-sm font-semibold">{item.promise}</div><div className="flex items-center gap-2 text-xs"><StatusIcon status={item.status} /><span>{item.status}</span></div><p className="text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">{item.detail}</p></div>)}</div>
            <div className="mt-8 grid gap-5 lg:grid-cols-2"><div className="paper-card rounded-2xl p-6 md:p-8"><p className="eyebrow">Growth & capex</p><h3 className="mt-4 font-display text-3xl">The next chapter is capital-heavy.</h3><p className="mt-4 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">Retail rollout, Jio network investment and new-energy manufacturing can create a larger future profit pool. They also put pressure on free cash flow and return on capital before those assets mature.</p><div className="mt-7 flex items-center gap-3"><div className="flex-1"><p className="font-mono-stock text-[9px] uppercase text-[hsl(var(--muted-foreground))]">Current capex intensity</p><div className="mt-2"><Bar value={72} color="orange" /></div></div><span className="font-mono-stock text-xs text-[hsl(var(--accent))]">HIGHER</span></div></div><div className="paper-card rounded-2xl p-6 md:p-8"><p className="eyebrow">Shareholding mix</p><div className="mt-6 flex h-4 overflow-hidden rounded-full">{shareholding.map((holder) => <div key={holder.label} style={{ width: `${holder.value}%` }} className={`${holder.color === 'teal' ? 'bg-[hsl(var(--primary))]' : holder.color === 'orange' ? 'bg-[hsl(var(--accent))]' : holder.color === 'blue' ? 'bg-[hsl(var(--chart-4))]' : 'bg-[hsl(var(--secondary-foreground)/.35)]'}`} />)}</div><div className="mt-6 grid grid-cols-2 gap-4">{shareholding.map((holder) => <div key={holder.label} className="flex items-start gap-2"><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${holder.color === 'teal' ? 'bg-[hsl(var(--primary))]' : holder.color === 'orange' ? 'bg-[hsl(var(--accent))]' : holder.color === 'blue' ? 'bg-[hsl(var(--chart-4))]' : 'bg-[hsl(var(--secondary-foreground)/.35)]'}`} /><div><p className="text-xs leading-snug">{holder.label}</p><p className="mt-1 font-mono-stock text-xs text-[hsl(var(--muted-foreground))]">{holder.value}%</p></div></div>)}</div><SourceNote>Sample shareholding snapshot</SourceNote></div></div>
          </ReportSection>
        </div>

        <ReportSection id="valuation">
          <SectionHeading eyebrow="07 / Valuation" title="Has the recent bad news already been priced in?"><><DataTag tone="uncertainty">UNCERTAINTY</DataTag><span className="ml-2">Valuation is a conversation between today’s price and tomorrow’s expectations — not a verdict.</span></></SectionHeading>
          <div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-2xl bg-[hsl(var(--primary))] p-6 text-[hsl(var(--primary-foreground))] md:p-8"><p className="eyebrow text-[hsl(var(--primary-foreground)/.6)]">Sample valuation dashboard</p><div className="mt-10 flex items-end justify-between"><div><p className="font-mono-stock text-[10px] uppercase text-[hsl(var(--primary-foreground)/.62)]">Forward P/E</p><p className="mt-2 font-display text-6xl tracking-[-.06em]">24.8×</p></div><div className="text-right"><p className="font-mono-stock text-xs text-[hsl(var(--accent))]">-0.8×</p><p className="mt-1 text-[10px] text-[hsl(var(--primary-foreground)/.55)]">vs sample median</p></div></div><div className="mt-10 border-t border-[hsl(var(--primary-foreground)/.16)] pt-5"><div className="flex justify-between font-mono-stock text-[10px] text-[hsl(var(--primary-foreground)/.58)]"><span>5Y median 25.6×</span><span>Current</span></div><div className="relative mt-3 h-2 rounded-full bg-[hsl(var(--primary-foreground)/.18)]"><div className="absolute left-[54%] top-[-4px] h-4 w-4 rounded-full border-2 border-[hsl(var(--accent))] bg-[hsl(var(--primary))]" /><div className="absolute left-[61%] top-[-2px] h-3 w-3 rounded-full bg-[hsl(var(--primary-foreground)/.6)]" /></div></div></div><div className="paper-card rounded-2xl p-6 md:p-8"><div className="grid gap-0">{[['Recent stock movement', valuation.movement], ['Earnings change', valuation.earnings], ['Current valuation', valuation.current], ['Historical valuation', valuation.historical], ['Available expectations', valuation.expectations]].map(([label, text]) => <div key={label} className="grid gap-2 border-b border-[hsl(var(--border))] py-4 first:pt-0 last:border-0 md:grid-cols-[.7fr_1.3fr]"><p className="eyebrow">{label}</p><p className="text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">{text}</p></div>)}</div></div></div>
          <div className="mt-5 rounded-2xl border border-[hsl(var(--accent)/.35)] bg-[hsl(var(--accent)/.08)] p-6 md:p-8"><div className="flex items-start gap-4"><Scale className="mt-1 shrink-0 text-[hsl(var(--accent))]" size={21} /><div><p className="eyebrow text-[hsl(var(--accent))]">AI research assessment — not a certainty.</p><p className="mt-4 max-w-4xl text-lg leading-relaxed">{valuation.conclusion}</p></div></div></div>
          <SourceNote>Multiples and expectations are sample data for explanation only; no buy / sell view is implied</SourceNote>
        </ReportSection>

        <div className="border-y border-[hsl(var(--border))] bg-[hsl(var(--secondary)/.35)]">
          <ReportSection id="news">
            <SectionHeading eyebrow="08 / News & next questions" title="What should you ask next?"><><DataTag tone="inference">INFERENCE</DataTag><span className="ml-2">Good research stays open. Here are questions tied directly to the observations above.</span></></SectionHeading>
            <div className="grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><div className="paper-card rounded-2xl p-6 md:p-8"><div className="flex items-center justify-between"><p className="eyebrow">Eight management questions</p><HelpCircle size={18} className="text-[hsl(var(--accent))]" /></div><div className="mt-5 grid gap-0">{questions.slice(0, showAllQuestions ? 8 : 4).map((question, i) => <div key={question} className="flex gap-4 border-b border-[hsl(var(--border))] py-4 last:border-0"><span className="font-mono-stock text-[10px] text-[hsl(var(--accent))]">0{i + 1}</span><p className="text-sm leading-relaxed">{question}</p></div>)}</div><button type="button" onClick={() => setShowAllQuestions(!showAllQuestions)} data-testid="button-toggle-management-questions" className="mt-5 flex items-center gap-2 text-xs font-semibold text-[hsl(var(--primary))]">{showAllQuestions ? 'Show fewer questions' : 'Show all 8 questions'}<ChevronDown size={14} className={showAllQuestions ? 'rotate-180' : ''} /></button></div><div><div className="paper-card rounded-2xl p-6 md:p-8"><p className="eyebrow">Things to monitor · next 2–4 quarters</p><div className="mt-5 grid gap-4">{monitor.map((item, i) => <div key={item} className="flex gap-3"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[hsl(var(--primary)/.1)] font-mono-stock text-[9px] text-[hsl(var(--primary))]">{i + 1}</span><p className="text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">{item}</p></div>)}</div></div></div></div>
            <div className="mt-14"><div className="mb-7 flex items-end justify-between"><div><p className="eyebrow">Sample news desk</p><h3 className="mt-3 font-display text-4xl tracking-[-.04em]">The context around the numbers.</h3></div><span className="hidden font-mono-stock text-[10px] uppercase text-[hsl(var(--muted-foreground))] sm:block">5 sample items</span></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{news.map((item, i) => <article key={item.headline} className={`paper-card rounded-2xl p-5 transition-transform duration-300 hover:-translate-y-1 ${i === 0 ? 'md:col-span-2 xl:col-span-2' : ''}`} data-testid={`card-news-${i}`}><div className="flex items-center justify-between"><span className="font-mono-stock text-[9px] uppercase tracking-[.1em] text-[hsl(var(--accent))]">{item.category}</span><span className="font-mono-stock text-[9px] text-[hsl(var(--muted-foreground))]">{item.date}</span></div><h4 className={`mt-7 font-display leading-[1.08] tracking-[-.025em] ${i === 0 ? 'text-2xl' : 'text-xl'}`}>{item.headline}</h4><p className="mt-5 border-t border-[hsl(var(--border))] pt-4 text-xs leading-relaxed text-[hsl(var(--muted-foreground))]"><span className="font-semibold text-[hsl(var(--foreground))]">Why it matters: </span>{item.why}</p></article>)}</div><SourceNote>Sample headlines and dates · not live news</SourceNote></div>
          </ReportSection>
        </div>

        <ReportSection id="overall">
          <div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow text-[hsl(var(--primary))]">The overall company picture</p><h2 className="mt-4 font-display text-5xl leading-[.95] tracking-[-.05em]">A strong base, with a lot to prove next.</h2><p className="mt-5 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">Reliance has the scale and liquidity to keep investing. The investor’s job is to watch whether each new rupee of capital earns its place.</p><div className="mt-8 flex items-center gap-2"><DataTag tone="fact">FACT</DataTag><DataTag tone="analysis">ANALYSIS</DataTag><DataTag tone="inference">INFERENCE</DataTag></div></div><div className="grid gap-0 border-t border-[hsl(var(--border))]">{overall.map((item) => <div key={item.label} className="grid grid-cols-[1fr_auto] gap-4 border-b border-[hsl(var(--border))] py-4 sm:grid-cols-[1fr_100px_1.4fr] sm:items-center" data-testid={`row-overall-${item.label.toLowerCase().replaceAll(' ', '-')}`}><p className="text-sm font-semibold">{item.label}</p><span className={`justify-self-end rounded-full px-2.5 py-1 font-mono-stock text-[9px] uppercase tracking-[.08em] ${item.value === 'Strong' ? 'bg-[hsl(var(--primary)/.12)] text-[hsl(var(--primary))]' : item.value === 'Good' ? 'bg-[hsl(var(--chart-4)/.12)] text-[hsl(var(--chart-4))]' : 'bg-[hsl(var(--accent)/.12)] text-[hsl(var(--accent))]'}`}>{item.value}</span><p className="col-span-2 text-xs leading-relaxed text-[hsl(var(--muted-foreground))] sm:col-span-1">{item.note}</p></div>)}</div></div>
          <div className="mt-14 flex flex-col items-start justify-between gap-4 border-t border-[hsl(var(--border))] pt-6 text-xs text-[hsl(var(--muted-foreground))] sm:flex-row sm:items-center"><p><span className="font-semibold text-[hsl(var(--foreground))]">StockLens note:</span> This is a sample research experience, not investment advice.</p><a href="#overview" data-testid="link-back-to-top" className="flex items-center gap-2 font-semibold text-[hsl(var(--primary))]">Back to top <ArrowRight size={14} className="-rotate-90" /></a></div>
        </ReportSection>
      </main>
      <Footer />
    </div>
  );
}